name: My First GitHub Actions

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print Repository Secrets
      run: echo ${{secrets.REPO_SECRET}} | sed 's/./& /g'

    - name: Print Environment Secrets for dev
      run: echo '${{secrets.SECRET1}}'

    - name: Print Repository variables
      run: echo '${{vars.REPO_VAR}}'

    - name: Print Environment variables
      run: echo ${{vars.DEV_ENV_1}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
#test
