name: My First GitHub Actions

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: checking secrets
      run: echo ${{secrets.REPO_SECRET}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
#testing the self hosted runner
